name: pytorch_food_vision
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8  # or your preferred Python version
  - numpy=1.21.2
  - pandas=1.3.3
  - matplotlib=3.4.3
  - pytorch=1.9.0
  - torchvision=0.10.0
  - gradio=2.2.0  # For deploying the model with Gradio
  - pip  # Use pip to install packages not available in conda
  - pip:
      - scikit-learn==0.24.2
      - Pillow==8.3.1  # Image processing for PyTorch models
